language: php
php:
  - '7.1'

before_script:
  - sudo apt-get install libzmq3-dev
  - pecl update-channels
  - echo "" | pecl install zmq-beta
  - cp .env.testing.example .env.testing
  - composer install --no-interaction --prefer-source